// src/components/flags.ts
//
// Country flag emoji for the admin console, extracted from the app's country
// list so both surfaces use the exact same source. Emoji flags need no image
// files and render crisply at any size. flagEmoji(code) returns the flag for a
// lowercase ISO 3166-1 alpha-2 code, or '🏳️' as a neutral fallback.

const FLAG_BY_CODE: Record<string, string> = {"af":"🇦🇫","al":"🇦🇱","dz":"🇩🇿","as":"🇦🇸","ad":"🇦🇩","ao":"🇦🇴","ai":"🇦🇮","ag":"🇦🇬","ar":"🇦🇷","am":"🇦🇲","aw":"🇦🇼","au":"🇦🇺","at":"🇦🇹","az":"🇦🇿","bs":"🇧🇸","bh":"🇧🇭","bd":"🇧🇩","bb":"🇧🇧","by":"🇧🇾","be":"🇧🇪","bz":"🇧🇿","bj":"🇧🇯","bm":"🇧🇲","bt":"🇧🇹","bo":"🇧🇴","ba":"🇧🇦","bw":"🇧🇼","br":"🇧🇷","bn":"🇧🇳","bg":"🇧🇬","bf":"🇧🇫","bi":"🇧🇮","cv":"🇨🇻","kh":"🇰🇭","cm":"🇨🇲","ca":"🇨🇦","ky":"🇰🇾","cf":"🇨🇫","td":"🇹🇩","cl":"🇨🇱","cn":"🇨🇳","co":"🇨🇴","km":"🇰🇲","cg":"🇨🇬","cd":"🇨🇩","cr":"🇨🇷","hr":"🇭🇷","cu":"🇨🇺","cw":"🇨🇼","cy":"🇨🇾","cz":"🇨🇿","ci":"🇨🇮","dk":"🇩🇰","dj":"🇩🇯","dm":"🇩🇲","do":"🇩🇴","ec":"🇪🇨","eg":"🇪🇬","sv":"🇸🇻","gq":"🇬🇶","er":"🇪🇷","ee":"🇪🇪","sz":"🇸🇿","et":"🇪🇹","fj":"🇫🇯","fi":"🇫🇮","fr":"🇫🇷","gf":"🇬🇫","pf":"🇵🇫","ga":"🇬🇦","gm":"🇬🇲","ge":"🇬🇪","de":"🇩🇪","gh":"🇬🇭","gi":"🇬🇮","gr":"🇬🇷","gl":"🇬🇱","gd":"🇬🇩","gp":"🇬🇵","gu":"🇬🇺","gt":"🇬🇹","gg":"🇬🇬","gn":"🇬🇳","gw":"🇬🇼","gy":"🇬🇾","ht":"🇭🇹","hn":"🇭🇳","hk":"🇭🇰","hu":"🇭🇺","is":"🇮🇸","in":"🇮🇳","id":"🇮🇩","ir":"🇮🇷","iq":"🇮🇶","ie":"🇮🇪","im":"🇮🇲","il":"🇮🇱","it":"🇮🇹","jm":"🇯🇲","jp":"🇯🇵","je":"🇯🇪","jo":"🇯🇴","kz":"🇰🇿","ke":"🇰🇪","ki":"🇰🇮","kw":"🇰🇼","kg":"🇰🇬","la":"🇱🇦","lv":"🇱🇻","lb":"🇱🇧","ls":"🇱🇸","lr":"🇱🇷","ly":"🇱🇾","li":"🇱🇮","lt":"🇱🇹","lu":"🇱🇺","mo":"🇲🇴","mg":"🇲🇬","mw":"🇲🇼","my":"🇲🇾","mv":"🇲🇻","ml":"🇲🇱","mt":"🇲🇹","mh":"🇲🇭","mq":"🇲🇶","mr":"🇲🇷","mu":"🇲🇺","mx":"🇲🇽","fm":"🇫🇲","md":"🇲🇩","mc":"🇲🇨","mn":"🇲🇳","me":"🇲🇪","ms":"🇲🇸","ma":"🇲🇦","mz":"🇲🇿","mm":"🇲🇲","na":"🇳🇦","nr":"🇳🇷","np":"🇳🇵","nl":"🇳🇱","nc":"🇳🇨","nz":"🇳🇿","ni":"🇳🇮","ne":"🇳🇪","ng":"🇳🇬","nu":"🇳🇺","kp":"🇰🇵","mk":"🇲🇰","no":"🇳🇴","om":"🇴🇲","pk":"🇵🇰","pw":"🇵🇼","ps":"🇵🇸","pa":"🇵🇦","pg":"🇵🇬","py":"🇵🇾","pe":"🇵🇪","ph":"🇵🇭","pl":"🇵🇱","pt":"🇵🇹","pr":"🇵🇷","qa":"🇶🇦","ro":"🇷🇴","ru":"🇷🇺","rw":"🇷🇼","re":"🇷🇪","bl":"🇧🇱","kn":"🇰🇳","lc":"🇱🇨","mf":"🇲🇫","vc":"🇻🇨","ws":"🇼🇸","sm":"🇸🇲","sa":"🇸🇦","sn":"🇸🇳","rs":"🇷🇸","sc":"🇸🇨","sl":"🇸🇱","sg":"🇸🇬","sx":"🇸🇽","sk":"🇸🇰","si":"🇸🇮","sb":"🇸🇧","so":"🇸🇴","za":"🇿🇦","kr":"🇰🇷","ss":"🇸🇸","es":"🇪🇸","lk":"🇱🇰","sd":"🇸🇩","sr":"🇸🇷","se":"🇸🇪","ch":"🇨🇭","sy":"🇸🇾","st":"🇸🇹","tw":"🇹🇼","tj":"🇹🇯","tz":"🇹🇿","th":"🇹🇭","tl":"🇹🇱","tg":"🇹🇬","to":"🇹🇴","tt":"🇹🇹","tn":"🇹🇳","tm":"🇹🇲","tc":"🇹🇨","tv":"🇹🇻","tr":"🇹🇷","ug":"🇺🇬","ua":"🇺🇦","ae":"🇦🇪","gb":"🇬🇧","us":"🇺🇸","uy":"🇺🇾","uz":"🇺🇿","vu":"🇻🇺","va":"🇻🇦","ve":"🇻🇪","vn":"🇻🇳","vg":"🇻🇬","vi":"🇻🇮","ye":"🇾🇪","zm":"🇿🇲","zw":"🇿🇼","ax":"🇦🇽"};

export function flagEmoji(code?: string | null): string {
  if (!code) return "🏳️";
  return FLAG_BY_CODE[code.toLowerCase()] || "🏳️";
}